collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8914894
  brandStrength: 0.3055494
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#BFEDFF'
    - '#527FC7'
    - '#86B9EC'
    - '#3E3E3C'
  rhythmicContrast: 0.04154694
typography_spectrum: 0.948926
layout_spectrum: 0.7021276
name: Chappy Happy
